[workspace]
members = [
    "crates/brewdb-bin",
    "crates/brewdb-catalog",
    "crates/brewdb-common",
    "crates/brewdb-execution",
    "crates/brewdb-frontend",
    "crates/brewdb-parser",
    "crates/brewdb-planner",
    "crates/brewdb-prost",
    "crates/brewdb-sqllogictests",
    "crates/brewdb-storage",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/qusijun/BrewDB"
rust-version = "1.88"

[workspace.dependencies]
arrow-schema = "58.4.0"
arrow = "58.4.0"
arrow-select = "58.4.0"
async-trait = "0.1.89"
datafusion = { version = "54.1.0", default-features = false, features = ["parquet", "sql"] }
datafusion-common = "54.1.0"
datafusion-expr = "54.1.0"
datafusion-functions = "54.1.0"
datafusion-functions-aggregate = "54.1.0"
datafusion-optimizer = "54.0.0"
datafusion-physical-expr = "54.1.0"
futures = "0.3.31"
inventory = "0.3.21"
log = "0.4"
paimon = "0.2.0"
prost = "0.14"
reqwest = { version = "0.12.28", default-features = false, features = ["http2", "json", "rustls-tls"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0"
sqlparser_derive = "0.5.0"
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
toml = "0.9.7"
tracing = "0.1.41"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "fmt", "json", "tracing-log"] }
sqllogictest = "0.29.1"
url = "2.5.8"
uuid = { version = "1.18.1", features = ["v4"] }
