[workspace]
members = [
    "crates/brewdb-common",
    "crates/brewdb-catalog",
    "crates/brewdb-frontend",
    "crates/brewdb-sql",
    "crates/brewdb-execution",
    "crates/brewdb-storage",
    "crates/brewdb-runtime",
    "bin/brewdbd",
    "bin/brewdb",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/qusijun/BrewDB"
rust-version = "1.88"

[workspace.dependencies]
arrow-schema = "58.4.0"
inventory = "0.3.21"
paimon = "0.2.0"
reqwest = { version = "0.12.28", default-features = false, features = ["http2", "json", "rustls-tls"] }
serde = { version = "1.0.229", features = ["derive"] }
toml = "0.9.7"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "fmt", "json"] }
url = "2.5.8"
uuid = { version = "1.18.1", features = ["v4"] }
