[package]
name = "brewdb-sqllogictests"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[test]]
name = "integration_tests"
path = "bin/integration_tests.rs"
harness = false

[dependencies]
brewdb-common = { path = "../brewdb-common", features = ["test-utils"] }
sqllogictest.workspace = true
