[package]
name = "brewdb-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
brewdb-core = { path = "../brewdb-core" }
brewdb-catalog = { path = "../brewdb-catalog" }
brewdb-execution = { path = "../brewdb-execution" }
