[package]
name = "brewdb-sql"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
brewdb-common = { path = "../brewdb-common" }
brewdb-catalog = { path = "../brewdb-catalog" }
datafusion-sql = "54.0.0"
uuid.workspace = true
