[package]
name = "brewdb-sql-parser"
version.workspace = true
edition = "2021"
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors = ["Apache DataFusion <dev@datafusion.apache.org>"]
description = "BrewDB SQL parser fork based on Apache DataFusion sqlparser-rs"
homepage = "https://github.com/apache/datafusion-sqlparser-rs"
documentation = "https://docs.rs/sqlparser/"
keywords = [
    "ansi",
    "sql",
    "lexer",
    "parser",
]

[features]
default = [
    "std",
    "recursive-protection",
]
derive-dialect = ["sqlparser_derive"]
json_example = [
    "serde_json",
    "serde",
]
recursive-protection = [
    "std",
    "recursive",
]
std = []
visitor = ["sqlparser_derive"]

[lib]
name = "brewdb_sql_parser"
path = "src/lib.rs"

[dependencies.bigdecimal]
version = "0.4.1"
features = ["serde"]
optional = true

[dependencies.log]
version = "0.4"

[dependencies.recursive]
version = "0.1.1"
optional = true

[dependencies.serde]
version = "1.0"
features = [
    "derive",
    "alloc",
]
optional = true
default-features = false

[dependencies.serde_json]
version = "1.0"
optional = true

[dependencies.sqlparser_derive]
version = "0.5.0"
optional = true
