[package]
name = "brewdb-catalog"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
brewdb-common = { path = "../brewdb-common" }
datafusion-common.workspace = true
paimon.workspace = true
tracing.workspace = true
tokio.workspace = true
uuid.workspace = true
