[package]
name = "brewdb"
version.workspace = true
edition = "2021"
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = [
    "std",
    "recursive-protection",
]
derive-dialect = ["sqlparser_derive"]
json_example = [
    "serde_json",
    "serde",
]
recursive-protection = [
    "std",
    "recursive",
]
std = []
visitor = ["sqlparser_derive"]

[dependencies]
arrow = "58.4.0"
arrow-select = "58.4.0"
async-trait = "0.1.89"
bigdecimal = { version = "0.4.1", features = ["serde"], optional = true }
datafusion = { version = "54.1.0", default-features = false, features = ["sql"] }
datafusion-common = "54.1.0"
datafusion-expr = "54.1.0"
datafusion-functions = "54.1.0"
datafusion-functions-aggregate = "54.1.0"
datafusion-optimizer = "54.0.0"
datafusion-physical-expr = "54.1.0"
futures = "0.3.31"
inventory.workspace = true
log = "0.4"
paimon.workspace = true
prost = "0.14"
recursive = { version = "0.1.1", optional = true }
serde = { version = "1.0", features = ["derive", "alloc"], optional = true, default-features = false }
serde_json = { version = "1.0", optional = true }
sqlparser_derive = { version = "0.5.0", optional = true }
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
pretty_assertions = "1.4.1"

[build-dependencies]
prost-build = "0.14"
protoc-bin-vendored = "3"
