[package]
name = "brewdb-planner"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
arrow = "58.4.0"
brewdb-catalog = { path = "../brewdb-catalog" }
brewdb-common = { path = "../brewdb-common" }
brewdb-sql = { path = "../brewdb-sql" }
datafusion-common = "54.1.0"
datafusion-expr = "54.1.0"
datafusion-optimizer = "54.0.0"
datafusion = { version = "54.1.0", default-features = false, features = ["sql"] }
datafusion-functions = "54.1.0"
datafusion-functions-aggregate = "54.1.0"
datafusion-sql = "54.0.0"
brewdb-storage = { path = "../brewdb-storage" }
uuid.workspace = true
