[package]
name = "brewdb-frontend"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
brewdb-core = { path = "../brewdb-core" }
brewdb-execution = { path = "../brewdb-execution" }
brewdb-runtime = { path = "../brewdb-runtime" }
brewdb-sql = { path = "../brewdb-sql" }
